services:
  pwgen.lan:
    image: pwgen.lan:latest
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '1280:8000'
